export const applications = [
  {
    id: 1,
    position: "Frontend Developer",
    company: "PixelWave",
    status: "submitted",
    appliedDate: "3 days ago",
    location: "Austin, TX",
    salary: "$90k - $120k",
  },
  {
    id: 2,
    position: "Backend Engineer",
    company: "CloudNova",
    status: "reviewed",
    appliedDate: "1 day ago",
    location: "Remote",
    salary: "$110k - $140k",
  },
  {
    id: 3,
    position: "Data Scientist",
    company: "NeuroTech",
    status: "interviewing",
    appliedDate: "1 week ago",
    location: "New York, NY",
    salary: "$130k - $160k",
  },
  {
    id: 4,
    position: "UI/UX Designer",
    company: "DesignHub",
    status: "pending",
    appliedDate: "2 weeks ago",
    location: "San Francisco, CA",
    salary: "$80k - $110k",
  },
  {
    id: 5,
    position: "DevOps Engineer",
    company: "SkyStack",
    status: "offered",
    appliedDate: "4 days ago",
    location: "Seattle, WA",
    salary: "$120k - $150k",
  },
  {
    id: 6,
    position: "Machine Learning Engineer",
    company: "QuantumAI",
    status: "rejected",
    appliedDate: "3 weeks ago",
    location: "Remote",
    salary: "$140k - $180k",
  },
  {
    id: 7,
    position: "Mobile App Developer",
    company: "AppCraft",
    status: "withdrawn",
    appliedDate: "1 month ago",
    location: "Chicago, IL",
    salary: "$100k - $130k",
  },
  {
    id: 8,
    position: "Full Stack Developer",
    company: "BitForge",
    status: "submitted",
    appliedDate: "6 days ago",
    location: "Remote",
    salary: "$95k - $125k",
  },
  {
    id: 9,
    position: "Cybersecurity Analyst",
    company: "SecureNet",
    status: "reviewed",
    appliedDate: "5 days ago",
    location: "Washington, DC",
    salary: "$110k - $145k",
  },
  {
    id: 10,
    position: "Product Manager",
    company: "Innovexa",
    status: "interviewing",
    appliedDate: "2 days ago",
    location: "Boston, MA",
    salary: "$130k - $170k",
  },
  {
    id: 11,
    position: "QA Engineer",
    company: "TestLab",
    status: "pending",
    appliedDate: "3 weeks ago",
    location: "Los Angeles, CA",
    salary: "$75k - $105k",
  },
  {
    id: 12,
    position: "Cloud Engineer",
    company: "NimbusWorks",
    status: "offered",
    appliedDate: "4 weeks ago",
    location: "Remote",
    salary: "$125k - $155k",
  },
  {
    id: 13,
    position: "AI Researcher",
    company: "DeepSphere",
    status: "accepted",
    appliedDate: "1 week ago",
    location: "San Francisco, CA",
    salary: "$150k - $200k",
  },
  {
    id: 14,
    position: "Database Admin",
    company: "DataPrime",
    status: "rejected",
    appliedDate: "2 days ago",
    location: "Houston, TX",
    salary: "$100k - $135k",
  },
  {
    id: 15,
    position: "Software Architect",
    company: "CodeBase",
    status: "reviewed",
    appliedDate: "1 month ago",
    location: "San Diego, CA",
    salary: "$150k - $190k",
  },
  {
    id: 16,
    position: "Blockchain Developer",
    company: "ChainWorks",
    status: "submitted",
    appliedDate: "1 day ago",
    location: "Remote",
    salary: "$140k - $180k",
  },
  {
    id: 17,
    position: "Network Engineer",
    company: "FiberLink",
    status: "interviewing",
    appliedDate: "3 days ago",
    location: "Miami, FL",
    salary: "$95k - $125k",
  },
  {
    id: 18,
    position: "Technical Writer",
    company: "DocuTech",
    status: "pending",
    appliedDate: "4 days ago",
    location: "Remote",
    salary: "$70k - $95k",
  },
  {
    id: 19,
    position: "IT Support Specialist",
    company: "SupportPlus",
    status: "withdrawn",
    appliedDate: "2 weeks ago",
    location: "Denver, CO",
    salary: "$55k - $75k",
  },
  {
    id: 20,
    position: "Automation Engineer",
    company: "RoboCore",
    status: "offered",
    appliedDate: "3 days ago",
    location: "Detroit, MI",
    salary: "$110k - $140k",
  },
  {
    id: 21,
    position: "ML Ops Engineer",
    company: "MindFlow",
    status: "accepted",
    appliedDate: "5 days ago",
    location: "Seattle, WA",
    salary: "$130k - $165k",
  },
  {
    id: 22,
    position: "Frontend Developer",
    company: "SoftRoot",
    status: "rejected",
    appliedDate: "2 weeks ago",
    location: "Remote",
    salary: "$85k - $110k",
  },
  {
    id: 23,
    position: "Product Owner",
    company: "SprintLogic",
    status: "reviewed",
    appliedDate: "3 days ago",
    location: "San Jose, CA",
    salary: "$125k - $160k",
  },
  {
    id: 24,
    position: "SRE Engineer",
    company: "ReliantOps",
    status: "submitted",
    appliedDate: "1 week ago",
    location: "Remote",
    salary: "$140k - $175k",
  },
  {
    id: 25,
    position: "Backend Developer",
    company: "NextGenWeb",
    status: "pending",
    appliedDate: "4 days ago",
    location: "Atlanta, GA",
    salary: "$100k - $130k",
  },
  {
    id: 26,
    position: "AI Engineer",
    company: "VisionaryAI",
    status: "interviewing",
    appliedDate: "3 weeks ago",
    location: "Remote",
    salary: "$150k - $185k",
  },
  {
    id: 27,
    position: "Full Stack Engineer",
    company: "CoreBuilder",
    status: "offered",
    appliedDate: "1 week ago",
    location: "Los Angeles, CA",
    salary: "$115k - $145k",
  },
  {
    id: 28,
    position: "DevOps Specialist",
    company: "CloudSync",
    status: "reviewed",
    appliedDate: "5 days ago",
    location: "Remote",
    salary: "$120k - $150k",
  },
  {
    id: 29,
    position: "Data Engineer",
    company: "PipeData",
    status: "submitted",
    appliedDate: "2 days ago",
    location: "Chicago, IL",
    salary: "$120k - $155k",
  },
  {
    id: 30,
    position: "Java Developer",
    company: "CodeCraft",
    status: "rejected",
    appliedDate: "1 week ago",
    location: "Phoenix, AZ",
    salary: "$90k - $125k",
  },
  {
    id: 31,
    position: "React Developer",
    company: "Frontendify",
    status: "accepted",
    appliedDate: "6 days ago",
    location: "Remote",
    salary: "$95k - $130k",
  },
  {
    id: 32,
    position: "Cloud Security Engineer",
    company: "SecureCloud",
    status: "reviewed",
    appliedDate: "1 day ago",
    location: "Dallas, TX",
    salary: "$135k - $170k",
  },
  {
    id: 33,
    position: "Mobile Developer",
    company: "AppVerse",
    status: "interviewing",
    appliedDate: "2 weeks ago",
    location: "Denver, CO",
    salary: "$100k - $140k",
  },
  {
    id: 34,
    position: "Business Analyst",
    company: "InsightPro",
    status: "pending",
    appliedDate: "3 days ago",
    location: "Remote",
    salary: "$80k - $110k",
  },
  {
    id: 35,
    position: "Technical PM",
    company: "BuildTech",
    status: "offered",
    appliedDate: "1 week ago",
    location: "San Francisco, CA",
    salary: "$140k - $180k",
  },
];

export const savedJobs = Array.from({ length: 50 }, (_, i) => {
  const positions = [
    "Frontend Developer",
    "Backend Developer",
    "Fullstack Developer",
    "DevOps Engineer",
    "Product Manager",
    "UI/UX Designer",
    "QA Engineer",
  ];
  const companies = [
    "TechCorp",
    "InnovateCo",
    "CloudSystems",
    "NextGen Solutions",
    "AlphaBeta",
    "PixelWorks",
    "CodeCrafters",
  ];
  const locations = [
    "New York, NY",
    "San Francisco, CA",
    "Austin, TX",
    "Boston, MA",
    "Seattle, WA",
    "Chicago, IL",
    "Los Angeles, CA",
  ];
  const salaries = ["$80k - $100k", "$90k - $120k", "$100k - $130k", "$105k - $135k", "$120k - $150k", "$130k - $160k"];

  const savedDates = [
    "1 day ago",
    "2 days ago",
    "3 days ago",
    "1 week ago",
    "2 weeks ago",
    "3 weeks ago",
    "1 month ago",
  ];

  return {
    id: (i + 1).toString(),
    position: positions[Math.floor(Math.random() * positions.length)],
    company: companies[Math.floor(Math.random() * companies.length)],
    location: locations[Math.floor(Math.random() * locations.length)],
    salary: salaries[Math.floor(Math.random() * salaries.length)],
    savedDate: savedDates[Math.floor(Math.random() * savedDates.length)],
  };
});

export const genders = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
] as const;

export const skillsGroupOptions = [
  {
    heading: "Frontend Frameworks",
    options: [
      { value: "react", label: "React" },
      { value: "vue", label: "Vue.js" },
      { value: "angular", label: "Angular" },
      { value: "svelte", label: "Svelte" },
    ],
  },
  {
    heading: "Backend Technologies",
    options: [
      { value: "nodejs", label: "Node.js" },
      { value: "django", label: "Django" },
      { value: "rails", label: "Ruby on Rails" },
      { value: "spring", label: "Spring Boot" },
    ],
  },
  {
    heading: "Databases",
    options: [
      { value: "postgresql", label: "PostgreSQL" },
      { value: "mongodb", label: "MongoDB" },
      { value: "redis", label: "Redis" },
      { value: "mysql", label: "MySQL" },
    ],
  },
];

export const experienceOps = [
  { value: "0-1", label: "0-1 years" },
  { value: "2-3", label: "2-3 years" },
  { value: "3-4", label: "3-4 years" },
  { value: "4-5", label: "4-5 years" },
  { value: "5-7", label: "5-7 years" },
  { value: "6-8", label: "6-8 years" },
  { value: "8-10", label: "8-10 years" },
  { value: "10+", label: "10+ years" },
];

export const skillLevels = [
  { value: "entry-level", label: "Entry Level" },
  { value: "junior", label: "Junior" },
  { value: "mid-level", label: "Mid-Level" },
  { value: "senior", label: "Senior" },
  { value: "expert", label: "Expert" },
] as const;

export const companySizeOps = [
  { value: "1-10", label: "1-10 employees" },
  { value: "11-50", label: "11-50 employees" },
  { value: "51-200", label: "51-200 employees" },
  { value: "201-500", label: "201-500 employees" },
  { value: "501-1000", label: "501-1000 employees" },
  { value: "1000-5000", label: "1000-5000 employees" },
  { value: "5000+", label: "5000+ employees" },
] as const;

export const industries = [
  { value: "technology", label: "Technology" },
  { value: "healthcare", label: "Healthcare" },
  { value: "finance", label: "Finance" },
  { value: "education", label: "Education" },
  { value: "retail", label: "Retail" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "hospitality", label: "Hospitality" },
  { value: "construction", label: "Construction" },
  { value: "transportation", label: "Transportation" },
  { value: "energy", label: "Energy" },
] as const;

export const jobTypes = [
  { value: "full-time", label: "Full-time" },
  { value: "part-time", label: "Part-time" },
  { value: "cantact", label: "Contract" },
  { value: "emporary", label: "Temporary" },
  { value: "internship", label: "Internship" },
];

export const jobBenefits = [
  { label: "Health Insurance", value: "Health Insurance" },
  { label: "Life Insurance", value: "Life Insurance" },
  { label: "Remote Work", value: "Remote Work" },
  { label: "Paid Time Off (PTO)", value: "Paid Time Off (PTO)" },
  { label: "Work From Home", value: "Work From Home" },
  { label: "Flexible Schedule", value: "Flexible Schedule" },
  { label: "Performance Bonus", value: "Performance Bonus" },
  { label: "Yearly Increment", value: "Yearly Increment" },
  { label: "Retirement Plan", value: "Retirement Plan" },
  { label: "Lunch Provided", value: "Lunch Provided" },
  { label: "Snacks & Drinks", value: "Snacks & Drinks" },
  { label: "Transportation Allowance", value: "Transportation Allowance" },
  { label: "Medical Reimbursement", value: "Medical Reimbursement" },
  { label: "Stock Options (ESOP)", value: "Stock Options (ESOP)" },
  { label: "Employee Discount", value: "Employee Discount" },
  { label: "Parental Leave", value: "Parental Leave" },
  { label: "On-site Gym", value: "On-site Gym" },
  { label: "Training & Development", value: "Training & Development" },
  { label: "Professional Growth Support", value: "Professional Growth Support" },
  { label: "Internet Allowance", value: "Internet Allowance" },
  { label: "Housing Allowance", value: "Housing Allowance" },
  { label: "Commission Pay", value: "Commission Pay" },
];

export const languages = [
  { value: "english", label: "English" },
  { value: "bangla", label: "Bangla" },
  { value: "hindi", label: "Hindi" },
  { value: "urdu", label: "Urdu" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "mandarin", label: "Mandarin" },
  { value: "arabic", label: "Arabic" },
  { value: "russian", label: "Russian" },
  { value: "japanese", label: "Japanese" },
  { value: "portuguese", label: "Portuguese" },
];
